export default [
  "“Be careful who you call your friends. I’d rather have four quarters than one hundred pennies.”",
  "“A smile can get you far, but a smile with a gun can get you further.”",
  "“You’d be surprised if you knew some of the fellows I’ve got to take care of.”",
  "“I have built my organization upon fear.”",
  "“It seems like I’m responsible for every crime that takes place in this country.”",
  "“You can do more with a kind word and a gun than with just a kind word.”",
  "“The country wanted booze and I organized it. Why should I be called a public enemy?”",
  "“Some call it bootlegging. Some call it racketeering. I call it a business.”",
  "“They can’t collect legal taxes from illegal money.”",
  "“Public service is my motto.”",
  "“Now I know why tigers eat their young.”",
  "“All I ever did was supply a demand that was pretty popular.”",
  "“I am like any other man. All I do is supply a demand.”",
  "“I am just a businessman, giving the people what they want.”",
  "“Capitalism is the legitimate racket of the ruling class.”",
  "“Prohibition has made nothing but trouble.”",
];
